import React, { useState } from 'react';
import { X, Download, FileText, Check, Copy, Code, FileCode } from 'lucide-react';
import { PlanAnalysisResult } from '../types';

interface ExportReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  result: PlanAnalysisResult | null;
  query?: string;
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({
  isOpen,
  onClose,
  result,
  query,
}) => {
  const [copiedFormat, setCopiedFormat] = useState<string | null>(null);

  if (!isOpen || !result) return null;

  const generateMarkdown = () => {
    return `# SQLPulse Database Query Optimization & Performance Audit Report

**Date:** ${new Date().toISOString()}  
**Target Engine:** ${result.engine?.toUpperCase() || 'POSTGRESQL'}  
**Efficiency Score:** ${result.performanceScore} / 100  
**Execution Time:** ${result.executionTimeMs} ms  
**Total Planner Cost:** ${result.totalCost}  
**Cache Hit Ratio:** ${result.cacheHitRatioPercentage}% (${result.totalMemoryHits.toLocaleString()} memory hits / ${result.totalDiskReads.toLocaleString()} disk reads)

---

## 1. Query Statement
\`\`\`sql
${query || 'SELECT * FROM orders WHERE status = \'completed\';'}
\`\`\`

---

## 2. Identified Performance Bottlenecks (${result.bottlenecks.length})
${result.bottlenecks
  .map(
    (b, i) => `### ${i + 1}. [${b.severity}] ${b.title}
- **Relation:** \`${b.relationName || 'n/a'}\`
- **Metric:** ${b.metricLabel} = \`${b.metricValue}\`
- **Description:** ${b.description}
- **Recommendation:** ${b.recommendation}
${b.suggestedSql ? `\`\`\`sql\n${b.suggestedSql}\n\`\`\`` : ''}
`
  )
  .join('\n')}

---

## 3. Recommended Optimization Actions
${result.recommendations
  .map(
    (r, i) => `### Action ${i + 1}: ${r.title} (${r.impact} Impact)
${r.description}
${r.suggestedSql ? `\`\`\`sql\n${r.suggestedSql}\n\`\`\`` : ''}
`
  )
  .join('\n')}

---
*Generated by SQLPulse Universal Database Optimization Hub.*
`;
  };

  const handleDownload = (format: 'md' | 'json') => {
    let content = '';
    let filename = `sqlpulse_audit_report_${Date.now()}`;
    let mime = 'text/plain';

    if (format === 'md') {
      content = generateMarkdown();
      filename += '.md';
      mime = 'text/markdown';
    } else {
      content = JSON.stringify(result, null, 2);
      filename += '.json';
      mime = 'application/json';
    }

    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopy = (text: string, format: string) => {
    navigator.clipboard.writeText(text);
    setCopiedFormat(format);
    setTimeout(() => setCopiedFormat(null), 2000);
  };

  return (
    <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-50 flex items-center justify-center p-3 sm:p-4 overflow-y-auto">
      <div className="bg-white/95 rounded-2xl sm:rounded-3xl border border-purple-200/80 shadow-2xl max-w-2xl w-full p-4 sm:p-6 space-y-4 sm:space-y-6 max-h-[92vh] overflow-y-auto scrollbar-thin">
        
        <div className="flex items-center justify-between border-b border-purple-200/70 pb-3 sm:pb-4 gap-2">
          <div className="flex items-center gap-2.5 sm:gap-3">
            <div className="w-9 h-9 sm:w-10 sm:h-10 rounded-2xl bg-purple-100 flex items-center justify-center text-purple-700 shadow-sm shrink-0">
              <FileText className="w-4.5 h-4.5 sm:w-5 sm:h-5" />
            </div>
            <div>
              <h2 className="text-sm sm:text-base font-bold text-slate-900">
                Export Enterprise Database Audit Report
              </h2>
              <p className="text-[11px] sm:text-xs text-slate-500">
                Download or copy professional reports in Markdown or JSON format.
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-1.5 sm:p-2 rounded-xl text-slate-400 hover:text-slate-600 hover:bg-slate-100 transition shrink-0 active:scale-95"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          
          <div className="p-4 rounded-2xl border border-purple-200/80 bg-white space-y-3 shadow-sm">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <FileCode className="w-4 h-4 text-purple-600" />
                <h3 className="text-sm font-bold text-slate-900">Markdown (.md)</h3>
              </div>
              <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-purple-100 text-purple-800">
                Human-Readable
              </span>
            </div>
            <p className="text-xs text-slate-500 leading-relaxed">
              GitHub-ready markdown report with metrics, diagrams, recommendations, and safe SQL DDLs.
            </p>
            <div className="flex items-center gap-2 pt-1">
              <button
                onClick={() => handleDownload('md')}
                className="flex-1 px-3 py-1.5 rounded-xl text-xs font-bold bg-purple-600 hover:bg-purple-700 text-white transition flex items-center justify-center gap-1.5 shadow-sm"
              >
                <Download className="w-3.5 h-3.5" />
                Download .md
              </button>
              <button
                onClick={() => handleCopy(generateMarkdown(), 'md')}
                className="px-3 py-1.5 rounded-xl text-xs font-bold bg-purple-50 hover:bg-purple-100 text-purple-900 border border-purple-200 transition flex items-center gap-1"
              >
                {copiedFormat === 'md' ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                Copy
              </button>
            </div>
          </div>

          <div className="p-4 rounded-2xl border border-indigo-200/80 bg-white space-y-3 shadow-sm">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Code className="w-4 h-4 text-indigo-600" />
                <h3 className="text-sm font-bold text-slate-900">JSON (.json)</h3>
              </div>
              <span className="text-[10px] font-bold px-2 py-0.5 rounded bg-indigo-100 text-indigo-800">
                CI/CD Pipeline
              </span>
            </div>
            <p className="text-xs text-slate-500 leading-relaxed">
              Complete raw telemetry, graph nodes, bottlenecks, and execution metadata for automated linters.
            </p>
            <div className="flex items-center gap-2 pt-1">
              <button
                onClick={() => handleDownload('json')}
                className="flex-1 px-3 py-1.5 rounded-xl text-xs font-bold bg-indigo-600 hover:bg-indigo-700 text-white transition flex items-center justify-center gap-1.5 shadow-sm"
              >
                <Download className="w-3.5 h-3.5" />
                Download .json
              </button>
              <button
                onClick={() => handleCopy(JSON.stringify(result, null, 2), 'json')}
                className="px-3 py-1.5 rounded-xl text-xs font-bold bg-indigo-50 hover:bg-indigo-100 text-indigo-900 border border-indigo-200 transition flex items-center gap-1"
              >
                {copiedFormat === 'json' ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                Copy
              </button>
            </div>
          </div>
        </div>

        <div className="space-y-1.5">
          <span className="text-[10px] uppercase font-bold text-slate-500">Report Preview:</span>
          <pre className="bg-slate-950 text-slate-300 p-3 rounded-xl text-[11px] font-mono border border-slate-800 max-h-36 overflow-y-auto leading-relaxed">
            {generateMarkdown()}
          </pre>
        </div>
      </div>
    </div>
  );
};
